### ISSUE TITLE
Add support for shared object dynamic TCTIs

### ISSUE THREAD

**Issue by williamcroberts** [intel/tpm2-tools#350]
"Dynamic TCTIs" are not so dynamic. They require configure and link time support. For environments that do not wish to re-configure and recompile the tools, allow a method to specify tcti's as a shared library to load and execute. Perhaps something like:
```
--tcti=dynamic --path=/home/bob/lib/foo.so
```

**Comment by flihp** [comment]
This was a use case that motivated a TCTI design goal but it wasn't something we've managed to agree upon / specify yet. The issue is initializing the TCTI. Currently we've left this as an "open issue" and so API for a TCTIs initialization function could be anything e.g. the device and socket TCTIs have different function prototypes.

So the first thing to do would be for us to agree upon a prototype for a common TCTI initialization function. This makes passing configuration data to the init function difficult. For the tabrmd init I've provided one init function that takes no configuration parameters: [tss2_tcti_tabrmd_init](https://github.com/01org/tpm2-abrmd/blob/master/src/tcti-tabrmd.c#L511) and uses defaults defined internally. There's also another that allows passing config values: [tss2_tcti_tabrmd_init_full](https://github.com/01org/tpm2-abrmd/blob/master/src/tcti-tabrmd.c#L511).

If every TCTI supported this sort of default initialization function and it had a common name or some way of finding the symbol in the shared object then you could get a basic implementation of this feature. Passing configuration data would be the tricky part. I guess we could switch to having each TCTI use environment variables for them?

**Comment by williamcroberts** [comment]
You could do something like:
```
tcti_init(common, &keyword_args)
```
```
struct keyword_args {
    size_t len;
    struct {
        char *keyword;
       char *value;
    } kw_args[];
};
```

this way the arguments can just come off the command line and we don't need to deal with them.
```
--tcti=bar --tcti-args=foo=bar,boo=gadget,..."
```
Convert --tcti-args to a keyword list and hand it off.

**Comment by williamcroberts** [comment]
The nice thing about getting the arguments grouped into something tcti generic, is that the tools will no longer need to support the options individually, which frees up -p from port to be used for other things, like policy.

```
tpm2_<tool> --tcti=foo --tcti-args="port=123,address=127.0.0.1"
tpm2_<tool> --t foo -a="port=123,address=127.0.0.1"
```
