### ISSUE TITLE
nvread/write data handling

### ISSUE THREAD

**Issue by pohly** [intel/tpm2-tools#606]
https://github.com/01org/tpm2-tools/blob/master/man/tpm2_nvwrite.1.md only mentions "-f" in the example. I've not seen it actually documented anywhere on that branch, which probably should be fixed. It was documented in man/tpm2_nvwrite.8.in on the 2.X branch.

It should also be mentioned that -f writes the entire file into offset 0. Supporting an offset in the index (similar to tpm2_nvread -o) would make sense. Overriding the file size is probably less useful and would imply allowing also a different read offset in the file. Usually this will be a temporary file where the caller can ensure that it has the right content.

For tpm2_nvread I am unsure how the data is supposed to be handled. It looks like it gets formatted on stdout:
```
# tpm2_nvread -x 0x1500001 -a 0x40000001 -o 0 -s 8

The size of data:8
 68  65  6c  6c  6f  0a  ff  ff 
```

But that implies that shell scripts calling tpm2_nvread have to parse this undocumented output.

Worse, error messages also get dumped to stdout. They should always go to stderr. Example:
```
# tpm2_nvread -x 0x1500001 -a 0x40000001 >/dev/null
root@intel-corei7-64:~# tpm2_nvread -x 0x1500001 -a 0x40000001
Argument mismatched!
Please type "tpm2_nvread -h" get the usage!
```

**Comment by martinezjavier** [comment]
@pohly there are many points in your filled issue, I'll try to answer them separately:

1. The -f option was removed and now is a positional argument, the problem is that commit e84490479b5d ("tpm2_nvwrite: make -f an argument") forgot to update the example.

2. The tpm2_nvwrite tool now supports an offset in master after commit ed41c04dc106 ("tpm2_nvwrite: add starting offset"). You may try to backport to 2.X if you are interested in that feature for that version.

3. The tpm2_nvread command now has a -f option to write the data read from the NVRAM after commit 797d90f1e216 ("tpm2_nvread: Add "output" option (-f)"). Again you may want to backport to 2.X if you are interested.

4. Yeah, a lot of error printouts were just using printf() but *I think* we have changed that in master and now all the error messages are using LOG_ERR() that prints to the standard error.

**Comment by pohly** [comment]
Commit e844904 also incorrectly adds "If _FILE_ is not specified, it defaults to stdin.". That should say "stdout", I suppose?

Looks like master already does everything I suggested, it's just the documentation which needs to be fixed.

Clearly it doesn't help that I am testing with 2.1.0 while switching back and forth between documentation for master and 2.X :-/

**Comment by martinezjavier** [comment]
@pohly right, probably a copy & paste error.

Indeed, the tools weren't in a great shape so a lot of things were fixed for the next 3.X branch. Hopefully that would be released soon.

**Comment by williamcroberts** [comment]
@pohly thanks for pointing these out. The 3.X branch which will be using version [1.3](https://github.com/intel/tpm2-tss/releases/tag/1.3.0-rc0) of the tss and [1.1.1](https://github.com/intel/tpm2-abrmd/releases/tag/1.1.1) of abrmd.

FYI 3.X tools builds need this patch to tss for the make check target to work:
https://github.com/intel/tpm2-tss/pull/614 

With that said, the 3.X branch **should** have everything that master (25828) currently has
with the exception of the API breaking change on the tss that dropped that crazy b/t union:
https://github.com/intel/tpm2-tss/commit/a64c33eb58ff289e9cfb83448ec9e9cbb53dfe3e

So 3.X is shaping up to have all the features that you requested. I urge you to kick the tires and send patches/bugs our way for things to fix. I plan on cutting a 3.0-rc0 sometime within the week.
