### ISSUE TITLE
Clarify tpm2_unseal man page

### ISSUE THREAD

**Issue by electrickite** [intel/tpm2-tools#670]
The tpm2_unseal man page indicates that data can be passed to the command as an argument or on stdin. I don’t believe this is the case, ie. tpm2_unseal will only operate on a loaded object handle or an object context file.

The man page should be updated to remove the reference to direct data loading if that is no longer possible.

The section currently reads:

“tpm2_unseal(1) - performs a hash operation on FILE and returns the results. If FILE is not specified, then data is read from stdin.”

**Comment by martinezjavier** [comment]
@electrickite indeed, that's wrong. In fact all the description is not correct since tpm2_unseal following your quoted text it says:

```
If the results of the hash will be used in a signing operation that uses a restricted
signing key, then the ticket returned by this command can indicate that the hash
is safe to sign.
```

So this definitely seems like a copy & paste error that includes the description for the tpm2_hash command. And in fact, looking at commit 3ff5477ea0ff ("man: port tpm2_unseal to markdown") that ported the man page from roff to markdown you can see that the description in both formats don't match.

Would you be interested in proposing a pull request to fix this?

**Comment by williamcroberts** [comment]
If no one submits a PR to this by tomorrow ill drop a PR for this on master and the 3.X branch. I plan on cutting 3.0-rc2 12/4/17 and we definitely want this on 3.0.
