### ISSUE TITLE
 Package requirements (sapi >= 1.3.0 sapi < 2.0.0) were not met when installing tpm2-tools-3.0

### ISSUE THREAD

**Issue by aqinwenky** [intel/tpm2-tools#764]
When I was configuring  tpm2-tools-3.0, I was interrupted by a problem.  The problem is as follow:

```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SAPI... no
configure: error: Package requirements (sapi >= 1.3.0 sapi < 2.0.0) were not met:

Requested 'sapi >= 1.3.0' but version of sapi is 
You may find new versions of sapi at https://github.com/01org/TPM2.0-TSS

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SAPI_CFLAGS
and SAPI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```
How can I resolve this problem ? and I have installed tpm2-tss-1.3.0 successfully.

**Comment by martinezjavier** [comment]
@aqinwenky what does the following say on your system?

```
$ pkg-config --modversion sapi
```

**Comment by martinezjavier** [comment]
@aqinwenky also, how did you installed tpm2-tss-1.3.0? From a distro package, built from a cloned git repo, from a tarball, etc.

My educated guess is that you built it from the source tarball automatically generated from the git repo (https://github.com/intel/tpm2-tss/archive/1.3.0.tar.gz) rather than from the release tarball generated with make dist (https://github.com/intel/tpm2-tss/releases/download/1.3.0/tpm2-tss-1.3.0.tar.gz).

For the former, the `Version:` field in the `sapi.pc` won't be set since its value comes from the `PACKAGE_VERSION` variable in the `configure` script. This in turn is queried using the `git describe --tags --always --dirty` command.

But since there's no git repo (the `.git` dir is removed before generating the tarball), the command will fail and `PACKAGE_VERSION` won't be set.

For the later, the tarball is generated using the `make dist` target and a generated `configure` script is included that has `PACKAGE_VERSION` correctly set. So the `Version:` field in the `sapi.pc` will also be correctly set.

**Comment by aqinwenky** [comment]
yes, you are right,  I installed the version which is generated from the git repo. I have reinstalled the version generated from make dist , and it's work now, thanks so much for your help.

**Comment by martinezjavier** [comment]
You are welcome, could you please close the issue then?
